yolo_model:

  config_file:
    name: yolov3-voc.cfg
  weight_file:
    name: yolov3-voc-indoor-vicon2-multiple_50000.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - aeroplane
      - bicycle
      - gascan
      - boat
      - bottle
      - bus
      - car
      - pelican
      - chair
      - tableclosed
      - table
      - ladder
      - cart
      - motorbike
      - person
      - pottedplant
      - sheep
      - sofa
      - train
      - tvmonitor